### ISSUE TITLE
R&D Fedora server side derivatives storage strategy

### ISSUE THREAD

**Issue by lsitu** [ucsdlib/damspas-rd#11]
CC/Sufia stores all thumbnail/derivatives on local disk. This ticket will discover the potential support with Fedora server side thumbnails/derivatives storage.

Related issues: https://github.com/ucsdlib/encrypted-stream-name/issues/1, https://github.com/ucsdlib/dams5-cc-pilot/issues/43

**Comment by lsitu** [comment]
@mcritchlow I've created a [PR](https://github.com/ucsdlib/horton/pull/12) that persists thumbnail/derivatives to Fedora instead of local disk storage that CC/Sufia persists thumbnails. We've got a thumbnail, a preview file, and a service file persisted along with the master file on Fedora.

**Comment by mcritchlow** [comment]
@lsitu - possibly of interest, there was a refactoring of some of the code this depends on to extract out the derivative handling to a [service class](https://github.com/projecthydra-labs/hyrax/pull/288/commits/a38179c7840550770d565a6d57cc206fc1a33e8b).

**Comment by mcritchlow** [comment]
@lsitu i'm curious what your thoughts are on moving ahead with this. Should we wait until we have a viable test environment to do performance testing? It seems like we might have a related dependency on IIIF implementation as well, at least for images. If so, we could perhaps have you dig into IIIF next Sprint.

**Comment by lsitu** [comment]
@mcritchlow I believe it's still hard to make a final call for derivatives storage and potentially the master file storage. In Fedora 3, files are separated from Fedora, which is more convenient for migration and management. And now lots of institutions are looking for solutions to separate the files from Fedora. Maybe we can pay more attention to this approach too.
For IIIF, yes, it seems like a good option for us and I think we can implement it next. Thanks.

**Comment by mcritchlow** [comment]
After speaking with @lsitu, @rstanonik and @jhriv and Mike last week, and again with @lsitu today, we've decided to move forward with the following:

* We will use the default Fedora filesystem persistence strategy
* We will use the default Hyrax derivatives persistence strategy. Master/source files to go Fedora, derivatives are put on disk. This will require a share/directory agreed upon with OPS.

The basis for these decisions is to try and follow community conventions as much as possible. If we run into issues with these conventions in the future, we can re-evaluate each choice. But this sets us up well for easier setup, configuration, and upgrades over time.

Derivative presentation may ultimately end up leading us towards a caching layer with something like Varnish, memcache, etc. But we can cross that bridge when we get to it (likely with IIIF).
